version: '2.1'

#####################################################
# Sets up roomates stack
# front-end container
# database
# backend TODO
#####################################################

volumes:
  dbdata:

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always
    environment: 
      NODE_PATH: "/home/node/node_modules"
    volumes:
      - ./front-end:/opt

  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    env_file:
      - ".env.mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
