version: '2.1'

#####################################################
# This Docker Compose file contains one service
#    r8s front-end
#####################################################

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 10s
    #   retries: 10

    # redis:
    #     image: redis
    #     ports:
    #     - "6379:6379"
