version: '2.1'

#####################################################
# This Docker Compose file contains one service
#    r8s front-end
#####################################################

volumes:
  dbdata:

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always
    # redis:
    #     image: redis
    #     ports:
    #     - "6379:6379"

    # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    env_file:
      - ".env.mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
